version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks: 
      - node-network
    volumes:
      - ./infra/init:/docker-entrypoint-initdb.d/
  
  node:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - '3000:3000'
    networks: 
      - node-network
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
    depends_on:
      - postgres

networks: 
  node-network:
    driver: bridge  