name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GH_TOKEN }}
          checkName: build

      - name: Wait for e2e to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-e2e
        with:
          token: ${{ secrets.GH_TOKEN }}
          checkName: e2e

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Release
        if: steps.wait-for-build.outputs.conclusion == 'success' && steps.wait-for-e2e.outputs.conclusion == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --no-ci
